In [10]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt


In [46]:
x= np.arange(0,2*np.pi,1)
x,np.cos(x)
#x,f

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.]),
 array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029]))

In [47]:
np.abs(-2),np.sin(0), np.cos(0), np.exp(1)

(2, 0.0, 1.0, 2.7182818284590451)

In [50]:
x = np.arange(-10,10)
f = 10*np.exp(2*x)

In [55]:
plt.plot(x,f,'ro')
plt.plot(x,f)

AttributeError: module 'matplotlib' has no attribute 'plot'

In [56]:
def f2 (x):
    return x**3+2*X**2+16

In [58]:
def f (x):
    a=x**3+2*x**2
    a=a+8
    return a

x=np.arange(0,10)
x,f(0),f(x)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 8,
 array([  8,  11,  24,  53, 104, 183, 296, 449, 648, 899]))

In [59]:
f= lambda x: x**2

In [60]:
x= np.arange(0,10)
x,f(x)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]))

In [61]:
def suma (x):
    return x**2
suma(2)
    

4

In [62]:
suma(3)

9

In [63]:
def f2(x):
    return x**3+2*x**2+16

In [64]:
x= np.arange(0,10)
x,f(0),f(x)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0,
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]))

In [65]:
def f(x):
    a=x**3+2*x**2
    a=a+8
    return a
    
    

    

In [66]:
x= np.arange(0,10)
x,f(0),f(x)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 8,
 array([  8,  11,  24,  53, 104, 183, 296, 449, 648, 899]))

In [ ]:
p=lambda t: 10*np.exp(2*t)

def dp (pk,h):
    pk
    
    
    
    
    
    
    
    